FROM golang:1.19-alpine

RUN apk add --no-cache git

WORKDIR /app/fetch-srv

COPY ./go.mod .
COPY ./go.sum .

RUN go mod tidy

COPY ../. .

RUN go build -o ./out/fetch-srv .

EXPOSE 8998

CMD [ "./out/fetch-srv" ]